oreBaseURL=https://e-shop.alfaromeousa.com
encryptedURL=https://web-ihub.eshopdemo.net
# Browser selection: chrome, firefox, edge, safari
browser=chrome
env=prod
vehicleType=used
lead.verification.enabled=false
# Database configuration
db.host.uat=eshop-us-uat.cbh6amtvql51.us-east-1.rds.amazonaws.com
db.host.prod=eshop-prod.cbh6amtvql51.us-east-1.rds.amazonaws.com
db.port=3306
db.name=fca_ore
db.user=qa-ore
db.password=